# 1. Appending Data to a Vector

In [2]:
v = c(10, 20, 30)
names(v) = c('Naruto', 'Sasuke', 'Sakura')

print(v)

Naruto Sasuke Sakura 
    10     20     30 


In [3]:
v[['Sasuke']]

[1] 20

In [4]:
v['Naruto']

Naruto 
    10

* Nối 2 vector lại với nhau

In [7]:
v = c(1, 2, 3)
new_items = c(6, 7, 8)
new_vector = c(v, new_items)

cat(new_vector)

1 2 3 6 7 8

* Thêm một phần tử vào vector

In [9]:
v = c(1, 2, 3)
v[length(v) + 1] = 42

cat(v)

1 2 3 42

* Tuy nhiên, theo nhiều thử nghiệm, để thêm phần tử vào vector thì cách dưới đây work nhanh nhất

In [10]:
v = c(1, 2, 3)
v = c(v, 4)

cat(v)

1 2 3 4

In [11]:
w = c(5, 6, 7, 8)
v = c(v, w)

cat(v)

1 2 3 4 5 6 7 8

* Có thể thay đổi giá trị tại một index chỉ định trong vector

In [12]:
v = c(1, 2, 3)
v[1] = 10

v

[1] 10  2  3

In [13]:
v[10] = 9
v

[1] 10  2  3 NA NA NA NA NA NA  9

# 2. Inserting data into a vector
* Sử dụng hàm `append(<vector>, <giá trị thêm vào>, after=<thêm sau index nào>)`

In [14]:
append(1:10, 99, after=5)

[1]  1  2  3  4  5 99  6  7  8  9 10

In [17]:
append(1:10, 99, after=0) # thêm vào đầu

[1] 99  1  2  3  4  5  6  7  8  9 10

In [16]:
append(1:10, 99, after=1)

[1]  1 99  2  3  4  5  6  7  8  9 10

# 3. Understanding the recycling rule

In [18]:
1:6

[1] 1 2 3 4 5 6

In [19]:
1:3

[1] 1 2 3

In [20]:
1:6 + 1:3

[1] 2 4 6 5 7 9

In [24]:
print(cbind(1:6))

     [,1]
[1,]    1
[2,]    2
[3,]    3
[4,]    4
[5,]    5
[6,]    6


In [25]:
print(cbind(1:3))

     [,1]
[1,]    1
[2,]    2
[3,]    3


In [26]:
print(cbind(1:6, 1:3))

     [,1] [,2]
[1,]    1    1
[2,]    2    2
[3,]    3    3
[4,]    4    1
[5,]    5    2
[6,]    6    3


In [27]:
print(cbind(1:7, 1:3))

Warning message in cbind(1:7, 1:3):
“number of rows of result is not a multiple of vector length (arg 2)”


     [,1] [,2]
[1,]    1    1
[2,]    2    2
[3,]    3    3
[4,]    4    1
[5,]    5    2
[6,]    6    3
[7,]    7    1


# 4. Creating a factor (Categorical variable)
* Cơ bản là vector nhưng mang thêm một vài tính chất của `set()` trong Python dc lưu trữ trong trường `level`

In [1]:
f = factor(c("Win", "Win", "Lose", "Tie", "Win", "Lose"))

f

[1] Win  Win  Lose Tie  Win  Lose
Levels: Lose Tie Win

In [2]:
wday = c("Wed", "Thu", "Mon", "Wed", "Thu", "Thu", "Thu", "Tue", "Thu", "Tue")
f = factor(wday)

f

[1] Wed Thu Mon Wed Thu Thu Thu Tue Thu Tue
Levels: Mon Thu Tue Wed

In [3]:
f = factor(wday, levels=c("Mon", "Tue", "Wed", "Thu", "Fri"))
f

[1] Wed Thu Mon Wed Thu Thu Thu Tue Thu Tue
Levels: Mon Tue Wed Thu Fri

# 5. Combining multiple vectors into one vector an a factor

In [6]:
freshmen = c(1, 2, 1, 1, 5)
sophomores = c(3, 2, 3, 3, 5)
juniors = c(5, 3, 4, 3, 3)

comb = stack(list(fresh=freshmen,
                 soph=sophomores,
                 jrs=juniors))

print(comb)

   values   ind
1       1 fresh
2       2 fresh
3       1 fresh
4       1 fresh
5       5 fresh
6       3  soph
7       2  soph
8       3  soph
9       3  soph
10      5  soph
11      5   jrs
12      3   jrs
13      4   jrs
14      3   jrs
15      3   jrs


In [7]:
aov(values~ind, data=comb)

Call:
   aov(formula = values ~ ind, data = comb)

Terms:
                      ind Residuals
Sum of Squares   6.933333 20.000000
Deg. of Freedom         2        12

Residual standard error: 1.290994
Estimated effects may be unbalanced

# 6. Creating a List

In [8]:
lst = list(0.5, 0.841, 0.977)
lst

[[1]]
[1] 0.5

[[2]]
[1] 0.841

[[3]]
[1] 0.977

In [12]:
lst = list(3.14, "Moe", c(1, 1, 3), mean)
lst

[[1]]
[1] 3.14

[[2]]
[1] "Moe"

[[3]]
[1] 1 1 3

[[4]]
function (x, ...) 
UseMethod("mean")
<bytecode: 0x561c278243a8>
<environment: namespace:base>

In [13]:
lst = list()
lst[[1]] = 3.14
lst[[2]] = "Moe"
lst[[3]] = c(1, 1, 2, 3)
lst[[4]] = mean

lst

[[1]]
[1] 3.14

[[2]]
[1] "Moe"

[[3]]
[1] 1 1 2 3

[[4]]
function (x, ...) 
UseMethod("mean")
<bytecode: 0x561c278243a8>
<environment: namespace:base>

In [14]:
lst = list(mid=0.5, right=0.841, far.right=0.977)

lst

$mid
[1] 0.5

$right
[1] 0.841

$far.right
[1] 0.977

# 7. Selecting List elements by Position

In [15]:
years = list(1960, 1964, 1976, 1994)

years

[[1]]
[1] 1960

[[2]]
[1] 1964

[[3]]
[1] 1976

[[4]]
[1] 1994

In [16]:
years[[1]]

[1] 1960

In [17]:
years[c(1, 2)]

[[1]]
[1] 1960

[[2]]
[1] 1964

In [18]:
class(years[[1]])

[1] "numeric"

In [19]:
class(years[1])

[1] "list"

In [20]:
cat(years[[1]], "Ahjhj")

1960 Ahjhj

In [21]:
cat(years[1], "Ahjhj")

ERROR: Error in cat(years[1], "Ahjhj"): argument 1 (type 'list') cannot be handled by 'cat'


# 8. Selecting List element by Name

In [22]:
years <- list(Kennedy = 1960, Johnson = 1964, Carter = 1976, Clinton = 1994)

years[['Kennedy']]

[1] 1960

In [23]:
years$Kennedy

[1] 1960

In [28]:
years[c('Kennedy', 'Johnson')]

$Kennedy
[1] 1960

$Johnson
[1] 1964

In [25]:
years['Carter']

$Carter
[1] 1976

# 9. Building a Name/Value Association List

In [29]:
values <- c(1, 2, 3)
names <- c("a", "b", "c")
lst <- list()
lst[names] <- values

lst

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [30]:
lst <- list(
    far.left = 0.023,
    left = 0.159,
    mid = 0.500,
    right = 0.841,
    far.right = 0.977
)

lst

$far.left
[1] 0.023

$left
[1] 0.159

$mid
[1] 0.5

$right
[1] 0.841

$far.right
[1] 0.977

In [31]:
lst <- list()

lst$far.left <- 0.023
lst$left <- 0.159
lst$mid <- 0.500
lst$right <- 0.841
lst$far.right <- 0.977

lst

$far.left
[1] 0.023

$left
[1] 0.159

$mid
[1] 0.5

$right
[1] 0.841

$far.right
[1] 0.977

In [32]:
values <- -2:2
names <- c("far.left", "left", "mid", "right", "far.right")

lst <- list()
lst[names] <- values

lst

$far.left
[1] -2

$left
[1] -1

$mid
[1] 0

$right
[1] 1

$far.right
[1] 2

In [33]:
cat("The left limit is", lst[["left"]], "\n")

The left limit is -1 


In [34]:
cat("The right limit is", lst[["right"]], "\n")

The right limit is 1 


In [36]:
for (nm in names(lst)) 
    cat("The", nm, "limit is", lst[[nm]], "\n")

The far.left limit is -2 
The left limit is -1 
The mid limit is 0 
The right limit is 1 
The far.right limit is 2 


# 10. Removing an Element from a List

In [37]:
years <- list(Kennedy = 1960, Johnson = 1964, Carter = 1976, Clinton = 1994)
years

$Kennedy
[1] 1960

$Johnson
[1] 1964

$Carter
[1] 1976

$Clinton
[1] 1994

In [38]:
years[["Johnson"]] <- NULL # Remove the element labeled "Johnson"

years

$Kennedy
[1] 1960

$Carter
[1] 1976

$Clinton
[1] 1994

In [39]:
years[c("Carter", "Clinton")] <- NULL # Remove two elements

years

$Kennedy
[1] 1960

# 11. Flattening a List into a Vector

In [40]:
iq.scores = list(100, 120, 103, 80, 99)
mean(iq.scores)

Warning message in mean.default(iq.scores):
“argument is not numeric or logical: returning NA”


[1] NA

> * Ko thể tính dc do `iq.scrores` ko phải là vector

In [41]:
mean(unlist(iq.scores))

[1] 100.4

In [42]:
cat(iq.scores, "\n")

ERROR: Error in cat(iq.scores, "\n"): argument 1 (type 'list') cannot be handled by 'cat'


In [44]:
cat(unlist(iq.scores), "are elements from list")

100 120 103 80 99 are elements from list

# 12. Removing NULL elements from a list

In [45]:
library(purrr)

In [46]:
lst = list("Moe", NULL, "Curly")
lst

[[1]]
[1] "Moe"

[[2]]
NULL

[[3]]
[1] "Curly"

In [47]:
compact(lst)

[[1]]
[1] "Moe"

[[2]]
[1] "Curly"

# 13. Removing List elements using a condition

In [48]:
lst = list(NA, 0, NA, 1, 2)

lst %>% discard(is.na)

[[1]]
[1] 0

[[2]]
[1] 1

[[3]]
[1] 2

In [51]:
lst <- list(3, "dog", 2, "cat", 1)
lst %>% discard(is.character)

[[1]]
[1] 3

[[2]]
[1] 2

[[3]]
[1] 1

In [53]:
is_na_or_null = function(x) {
    is.na(x) || is.null(x)
} 

lst = list(1, NA, 2, NULL, 3)

lst %>% discard(is_na_or_null)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

# 14. Initializing a Matrix

In [57]:
vec = 1:6

print(matrix(vec, 2, 3))

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [59]:
print(matrix(0, 2, 3))

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0


In [60]:
print(NA, 2, 3)

[1] NA


In [61]:
mat <- matrix(c(1.1, 1.2, 1.3, 2.1, 2.2, 2.3), 2, 3)

print(mat)

     [,1] [,2] [,3]
[1,]  1.1  1.3  2.2
[2,]  1.2  2.1  2.3


In [63]:
theData <- c(1.1, 1.2, 1.3, 2.1, 2.2, 2.3)
mat <- matrix(theData, 2, 3, byrow = TRUE)

print(mat)

     [,1] [,2] [,3]
[1,]  1.1  1.2  1.3
[2,]  2.1  2.2  2.3


In [66]:
v <- c(1.1, 1.2, 1.3, 2.1, 2.2, 2.3)
dim(v) <- c(2, 3)

print(v)

     [,1] [,2] [,3]
[1,]  1.1  1.3  2.2
[2,]  1.2  2.1  2.3


In [67]:
class(v)

[1] "matrix" "array"

# 15. Performing matrix operations

In [6]:
mat = matrix(c(2, 1, 1, 3, 2, 1, 2, 1, 2), nrow = 3, ncol = 3)

print(mat)

     [,1] [,2] [,3]
[1,]    2    3    2
[2,]    1    2    1
[3,]    1    1    2


In [7]:
print(t(mat))

     [,1] [,2] [,3]
[1,]    2    1    1
[2,]    3    2    1
[3,]    2    1    2


In [9]:
print(solve(mat)) # ma trận nghịch đảo

     [,1] [,2] [,3]
[1,]    3   -4   -1
[2,]   -1    2    0
[3,]   -1    1    1


In [12]:
print(mat %*% solve(mat))

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


In [15]:
print(diag(5)) # ma trận đơn vị

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    1    0    0    0
[3,]    0    0    1    0    0
[4,]    0    0    0    1    0
[5,]    0    0    0    0    1


# 16. Giving Descriptive Names to the Rows and Columns of a Matrix _(đặt tên cho hàng và cột của ma trận)_

In [16]:
mat = matrix(1:9, nrow=3, ncol=3)

print(mat)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [17]:
rownames(mat) = c("row_1", "row_2", "row_3")
colnames(mat) = c("col_1", "col_2", "col_3")

print(mat)

      col_1 col_2 col_3
row_1     1     4     7
row_2     2     5     8
row_3     3     6     9


In [18]:
mat['row_1', 'col_1']

[1] 1

# 17. Selecting One Row or Column from a Matrix _(chọn một hàng hoặc cột trong ma trận)_

In [19]:
mat = matrix(1:9, nrow=3, ncol=3)

print(mat)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


* Chọn dòng đầu tiên

In [20]:
mat[1,]

[1] 1 4 7

* Chọn cột thứ ba

In [21]:
mat[, 3]

[1] 7 8 9

* Trả về ma trận con bao gồm một hàng bằng cách chỉ định đối số `drop=FALSE`

In [23]:
mat[1,, drop=FALSE]

[,1] [,2] [,3]
[1,] 1    4    7

* Trả về ma trận con bao gồm một dòng

In [24]:
mat[, 3, drop=FALSE]

[,1]
[1,] 7   
[2,] 8   
[3,] 9

# 18. Initializing a Data Frame from Column Data _(khởi tạo dữ liệu cho dataframe)_

* Khởi tạo ko chỉ định tên cột

In [25]:
df = data.frame(1:3, 4:6, 7:9)

df

X1.3 X4.6 X7.9
1 1    4    7   
2 2    5    8   
3 3    6    9

* Khởi tạo có chỉ định tên cột

In [26]:
df = data.frame(col_1=1:3, col_2=4:6, col_3=7:9)

df

col_1 col_2 col_3
1 1     4     7    
2 2     5     8    
3 3     6     9

* Tạo dataframe từ list các vector

In [2]:
lst_of_vectors = list(p1=1:10, p2=11:20, p3=21:30)
df = as.data.frame(lst_of_vectors)

df

p1 p2 p3
1   1 11 21
2   2 12 22
3   3 13 23
4   4 14 24
5   5 15 25
6   6 16 26
7   7 17 27
8   8 18 28
9   9 19 29
10 10 20 30

# 19. Initializing a Data Frame from Row Data _(tạo dataframe từ các dòng dữ liệu)_

In [4]:
r1 <- data.frame(a = 1, b = 2, c = "X")
r2 <- data.frame(a = 3, b = 4, c = "Y")
r3 <- data.frame(a = 5, b = 6, c = "Z")

rbind(r1, r2, r3)

a b c
1 1 2 X
2 3 4 Y
3 5 6 Z

In [8]:
library(dplyr)

lst_of_rows = list(r1, r2, r3)

bind_rows(lst_of_rows)

a b c
1 1 2 X
2 3 4 Y
3 5 6 Z

In [9]:
l1 <- list(a = 1, b = 2, c = "X")
l2 <- list(a = 3, b = 4, c = "Y")
l3 <- list(a = 5, b = 6, c = "Z")
list.of.lists <- list(l1, l2, l3)

bind_rows(list.of.lists)

a b c
1 1 2 X
2 3 4 Y
3 5 6 Z

* `factor` trong dataframe

In [10]:
data.frame(a = 1, b = 2, c = "a", stringsAsFactors = FALSE)

a b c
1 1 2 a

In [11]:
l1 <- list( a=1, b=2, c='X' )
l2 <- list( a=3, b=4, c='Y' )
l3 <- list( a=5, b=6, c='Z' )
obs <- list(l1, l2, l3)
df <- do.call(rbind, Map(as.data.frame, obs))

In [12]:
df

a b c
1 1 2 X
2 3 4 Y
3 5 6 Z

In [13]:
i <- sapply(df, is.factor)
df[i] <- lapply(df[i], as.character)

df

a b c
1 1 2 X
2 3 4 Y
3 5 6 Z